app:
  name: "CodeHive"

server:
  host: "localhost"
  port: 9091

dataBase:
  typeDatabase: "sqlite"
  stringConnection: "SysConfig.db"

redis:
  host: "localhost"
  port: 6379

configAuth:
  host: "http://localhost"
  port: 9092
  endpoint: "/validate/token"