app:
  name: "CodeHive"

server:
  host: "localhost"
  port: 9092

dataBase:
  typeDatabase: "sqlite"
  stringConnection: "SysConfig.db"

redis:
  host: "localhost"
  port: 6379

configAuth:
  host: "localhost"
  port: 8081
  endpoint: "/validate/token"